version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    restart: unless-stopped
    command: "--bind_ip_all --replSet rs0"

volumes:
  mongo:
